---
name: Build C++ project

on:
  workflow_dispatch:
  pull_request:

jobs:
  test_cpp_build:
    runs-on: windows-latest
    name: Build C++ (winOS)
    steps:
      - name: Checkout Files
        uses: actions/checkout@v4.1.4
      - name: Install cmake
        shell: pwsh
        run: |
         choco install cmake
         cmake --version
      - name: Generate Cmake Configuration
        shell: pwsh
        run: |
          mkdir cpp_build
          cd cpp_build
          cmake .. -G"Unix Makefiles"
      - name: Build project
        shell: pwsh
#        working-directory: ./cpp_build
        run: |
          cd ./cpp_build
          make    
      - uses: actions/upload-artifact@v4
        with:
          name: cpp-build-output
          path: cpp_build
