---
name: Build C++ project

on:
  workflow_dispatch:
  pull_request:

jobs:
  test_cpp_build:
    runs-on: windows-latest
    env: 
      cmake-build-directory: ./cpp_build
    name: Build C++ (winOS)
    steps:
      - name: Checkout Files
        uses: actions/checkout@v4.1.4
      - name: Install cmake
        shell: pwsh
        run: |
         choco install cmake
         cmake --version
      - name: Generate Cmake Configuration
        shell: pwsh
        run: |
          mkdir ${{env.cpp_build}}
          cd ${{env.cpp_build}}
          cmake .. -G"Unix Makefiles"
          make          
