---
name: Build Cpp Project

on:
  workflow_dispatch:
  pull_request:

# run checkout as a dummy checkout 

jobs:
  build:
    name: Dummy run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
